### ISSUE TITLE
A potential bug in the code

### ISSUE THREAD

**Issue by wilburmao** [finsberg/ldrb#29] opened 2022-04-19 16:14 UTC
Hi Finsberg,

When I run the demo_lv.py code, I find that the resulting fiber orientations are not entirely expected. For example, when I use these parameters: alpha_endo_lv=60, alpha_epi_lv=-60, the fiber angle in the mid-layer should be consistent. But you can see that the fiber changes direction in the mid-layer. Only the top layer fibers in the z-direction are shown for clarity. 
![image](https://user-images.githubusercontent.com/60264411/164047935-56c9cc3f-fe4a-4dab-a688-b6d4920a478e.png)
Similarly, when alpha_endo_lv=0, alpha_epi_lv=-60, the mid-layer fibers also have inconsistent angles on the right.
![image](https://user-images.githubusercontent.com/60264411/164048589-d46732a4-bfc9-4068-b2d8-84b357e6251c.png)
When the alpha_endo_lv=-10, alpha_epi_lv=-60, the fibers in the mid-layer seem to be correct.
![image](https://user-images.githubusercontent.com/60264411/164048814-7492299f-fb6b-48d3-b16e-06d481abdbee.png)

**Comment by finsberg** [comment] 2022-04-19 20:05
Thanks @wilburmao.  I agree that this does looks strange. How does it look if you use another function space (say, CG2 or DG1)? Does this help?

**Comment by wilburmao** [comment] 2022-04-20 03:29
The results are about the same for different function spaces.

**Comment by jingbinzhao415** [comment] 2022-06-03 17:27
Hi Dr. Finsberg,

I have tested the updated version of ldrb. When I run the demo_lv.py code, some results of orientation are confused me. The fibers' orientation in the middle layer are expected as 0 degree, green arrows are what I expected. Below are my results.
example1
    alpha_endo_lv=60,  # Fiber angle on the endocardium
    alpha_epi_lv=-60,  # Fiber angle on the epicardium
    beta_endo_lv=0,  # Sheet angle on the endocardium
    beta_epi_lv=0,  # Sheet angle on the epicardium 

![image](https://user-images.githubusercontent.com/93218388/171912689-36de504e-4e99-4d75-86a3-6a100dc94252.png)

example2
    alpha_endo_lv=90,  # Fiber angle on the endocardium
    alpha_epi_lv=-90,  # Fiber angle on the epicardium
    beta_endo_lv=0,  # Sheet angle on the endocardium
    beta_epi_lv=0,  # Sheet angle on the epicardium

![image](https://user-images.githubusercontent.com/93218388/171914548-a3f76a5e-abd0-4b8d-817a-c83d70498e96.png)


Thank you in advanced for your help!

Best,
Jingbin

**Comment by finsberg** [comment] 2022-08-18 19:25
I agree that the fiber orientations in the middle layer, or to say it more precisely,  at the point where the radius is half way between ends and epi should be zero. Whether it is actually zero in the mesh you are using will depend on whether the nodes between endo and epi are located exactly half way between ends and epi. 

You can try to do this on a finer mesh and see if the problem still remains.

**Comment by finsberg** [comment] 2022-11-16 10:31
@wilburmao @jingbinzhao415 We just fixed a bug in ldrb. Could you check if the problem is fixed now, after upgrading to the latest version
```
python3 -m pip install ldrb --upgrade
```

**Comment by jingbinzhao415** [comment] 2022-11-16 18:06
Hi Dr. Finsberg,

@wilburmao   have checked it and the fiber looks good now. Thank you for your help!

**Comment by finsberg** [comment] 2022-11-16 18:07
Great! I am closing this now then

**Closed by finsberg** 2022-11-16 18:07 UTC
