### ISSUE TITLE
Bi-ventricular problem

### ISSUE THREAD

**Issue by jingbinzhao415** [finsberg/ldrb#46] opened 2022-11-16 18:54 UTC
Hi Dr. Finsberg,

Below is the test of bi-ventricular.  The angle of LV is 60 to -60 from endo to epi, and the angle of RV is 90 to -90 from endo to epi, we could see the angle of RV angle in endo region is still the -90 same as the angle of epi. 

![image](https://user-images.githubusercontent.com/93218388/202267704-029cd2af-fcd2-4f4d-80ce-891618230174.png)

**Comment by ivhak** [comment] 2022-12-12 10:04
I think this might be related to the tolerances used to determine whether or not to use `bislerp`:
https://github.com/finsberg/ldrb/blob/731e39c0b946d63509d207d7662ad6b36c919be7/ldrb/calculus.py#L107-L135

Removing the tolerance should fix this issue @finsberg. See the discussion of the same issue in the `lifex` repo: https://gitlab.com/lifex/lifex/-/issues/3

**Comment by finsberg** [comment] 2022-12-14 06:14
@ivhak Thank a lot for looking into this. I tried to apply your patch on the ellipsoidal BiV geometry (basically running the [following demo[https://github.com/finsberg/ldrb/blob/main/demos/demo_biv.py)) and I get the following fiber fields 

![patch](https://user-images.githubusercontent.com/2010323/207520170-cd6b85b2-3844-47c2-a08c-2d8f2a3fa1b0.png)

There seems to be something strange going on in the septum. Do you know if I need to change / remove the tolerance elsewhere?

**Comment by ivhak** [comment] 2022-12-14 12:13
Hmm, that looks weird. May be caused by the lines below. `tol` is used to determine whether we are in the left or right ventricle, and this is a place where it might actually make sense to have a tolerance, but I am not sure.

https://github.com/finsberg/ldrb/blob/9cb6b0eab256ab83c877b386fb3f300de25e07e9/ldrb/calculus.py#L258-L294

Or maybe this:

https://github.com/finsberg/ldrb/blob/9cb6b0eab256ab83c877b386fb3f300de25e07e9/ldrb/calculus.py#L107-L110

**Comment by finsberg** [comment] 2022-12-19 07:18
I have tried to fiddle a little bit with these tolerances and I do get this problem at the septum if I don't include this tolerance. Therefore I think I will keep the current version as it is. 

@jingbinzhao415 in what type of simulations are you using these fiber fields? In most cases the fiber orientations are bi-directional meaning that the problem you are describing is not really relevant because although the arrow is pointing downwards, the direction it is pointing is still correct. I will keep this issue open for others to see, but I will not spend more time on fixing this. Contributions are of course welcomed.

**Comment by finsberg** [comment] 2023-05-05 09:49
Fixed in https://github.com/finsberg/ldrb/pull/72

**Closed by finsberg** 2023-05-05 09:49 UTC
Labels: wontfix
